### ISSUE TITLE
Bottom half of "Login with netlify" button isn't clickable 

### ISSUE THREAD

**Issue by jai-dewani** [netlify/million-devs#36] opened 2020-08-03 19:20 UTC
**Problem:** The bottom half of Login with netlify button isn't clickable
**Plausible Reason:** I haven't really look closely at the source code, but since this problem was solved by removing my bookmark bar from bellow my address bar, it seems to be a problem with relative and absolute positioning of the button

I do have a video showing these results, I will update the link here after uploading it.

_Update:_ [Link to the video demonstrating the problem](https://drive.google.com/file/d/1tDVMgtwh5c06qy7aLJeVJL1xrkgrPyKe/view?usp=sharing)

_PS:_ I haven't used netlify much but from what I have, I love your product ❤️

**Comment by zachleat** [comment] 2020-08-03 21:08
Ah yes sorry I believe this is a duplicate of #26.

**Closed by zachleat** 2020-08-03 21:08 UTC
Labels: duplicate
